version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
      - "9070:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    build: .
    volumes:
      - ./code:/code
    environment:
      XDEBUG_CONFIG: 'remote_host=178.214.200.7 remote_enable=1'
      PHP_IDE_CONFIG: 'serverName = Docker'

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Vitalik*love23
      MYSQL_DATABASE: tasklist
    ports:
      - "3333:3306"

